//@version=4
study("Traders Dynamic Index and EMA Alerts", shorttitle="TDI_2EMA", overlay=true, max_lines_count=500, max_labels_count=500)

rsiPeriod = input(21, minval = 1, title = "RSI Period")
bbandLength = input(34, minval = 1, title = "Bolinger Bband Length")
lengthrsipl = input(7, minval = 0, title = "Fast MA on RSI")
lengthtradesl = input(2, minval = 1, title = "Slow MA on RSI")
highlightBreakouts = input(title="Highlight Breakouts ?", type=input.bool, defval=true)

src = close                                                             // Source of Calculations (Close of Bar)
rsi_close = rsi(src, rsiPeriod)                                         // RSI of Close
ma_cur = sma(rsi_close, bbandLength)                                    // Moving Average of RSI [current]
offs = (1.6185 * stdev(rsi_close, bbandLength))                                  // Offset
up = ma_cur + offs                                                          // Upper B bands
dn = ma_cur - offs                                                          // Lower B bands
mid = (up + dn) / 2                                                     // Average of Upper and Lower B bands
fastMA = sma(rsi_close, lengthrsipl)                                            // Moving Average of RSI 2 bars back
slowMA = sma(rsi_close, lengthtradesl)                                          // Moving Average of RSI 7 bars back

bb_upper = plot(up, "Upper Bolinger band", color = color.blue, linewidth = 1)               // Upper B band
bb_lower = plot(dn, "Lower Bolinger band", color = color.blue, linewidth = 1)               // Lower B band
//bb_midl = plot(mid, "Middle of Bolinger bands", color = color.white, linewidth = 1)      // Middle of B bands

//plot(slowMA, "Slow MA", color = #00AB08, linewidth=2)                       // Plot Slow MA
//plot(fastMA, "Fast MA", color = #ff0000, linewidth=2)                         // Plot Fast MA

//RSI PLOT

Color1 = rsi_close > rsi_close[1] ? color.green : color.red
Color2 = rsi_close >= up ? color.green : rsi_close <= dn ? color.red : color.orange

Color = highlightBreakouts ? Color2 : Color1

rsiPlot = plot(rsi_close, title="RSI", color=Color, transp=0, linewidth=2)

upperFillColor = rsi_close >= up and highlightBreakouts ? color.green : na
lowerFillColor = rsi_close <= dn and highlightBreakouts ? color.red : na

fill(bb_upper, rsiPlot, color=upperFillColor, transp=50)
fill(bb_lower, rsiPlot, color=lowerFillColor, transp=50)

// Breakout out of the B Bands
positiveCondTDI = (rsi_close > up) or crossover(up, rsi_close)
negativeCondTDI = (rsi_close < dn) or crossunder(dn, rsi_close)

plotshape(positiveCondTDI, color=Color, location=location.top, style=shape.circle, size=size.tiny, transp=50)
plotshape(negativeCondTDI, color=Color, location=location.top, style=shape.circle, size=size.tiny, transp=50)


// DEMA
exponential = input(true, title="Exponential MA")

ma50 = exponential ? ema(src, 50) : sma(src, 50)
ma200 = exponential ? ema(src, 200) : sma(src, 200)

plot(ma50, color=color.new(color.yellow, 0), title="[E]MA50")
plot(ma200, color=color.new(color.white, 0), title="[E]MA200")

if crossover(ma50, ma200)
    label.new(bar_index, na, text="Golden Cross", yloc=yloc.belowbar, color=color.gray, textcolor=color.yellow, style=label.style_xcross, size=size.small)
if crossunder(ma50, ma200)
    label.new(bar_index, na, text="Death Cross", yloc=yloc.abovebar, color=color.gray, textcolor=color.red, style=label.style_xcross, size=size.small)




//@version=5
indicator(shorttitle="BB", title="Bollinger Bands", overlay=true, timeframe="", timeframe_gaps=true)

length = input.int(20, minval=1)
src = input(close, title="Source")
mult = input.float(2.0, minval=0.001, maxval=50, title="StdDev")
basis = ta.sma(src, length)
dev = mult * ta.stdev(src, length)
upper = basis + dev
lower = basis - dev
offset = input.int(0, "Offset", minval = -500, maxval = 500)
plot(basis, "Basis", color=#FF6D00, offset = offset)
p1 = plot(upper, "Upper", color=#2962FF, offset = offset)
p2 = plot(lower, "Lower", color=#2962FF, offset = offset)
fill(p1, p2, title = "Background", color=color.rgb(33, 150, 243, 95))