// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © JanKoristka

//@version=4
study("TDI + RSI + BB [Market Makers Method]", shorttitle="MMM")

rsiPeriod = input(21, minval = 1, title = "RSI Period")
bandLength = input(34, minval = 1, title = "Band Length")
lengthrsipl = input(7, minval = 0, title = "Fast MA on RSI")
lengthtradesl = input(2, minval = 1, title = "Slow MA on RSI")

src = close                                                             // Source of Calculations (Close of Bar)
r = rsi(src, rsiPeriod)                                                 // RSI of Close
ma = sma(r, bandLength)                                                 // Moving Average of RSI [current]
offs = (1.6185 * stdev(r, bandLength))                                  // Offset
up = ma + offs                                                          // Upper Bands
dn = ma - offs                                                          // Lower Bands
mid = (up + dn) / 2                                                     // Average of Upper and Lower Bands
fastMA = sma(r, lengthrsipl)                                            // Moving Average of RSI 2 bars back
slowMA = sma(r, lengthtradesl)                                          // Moving Average of RSI 7 bars back

hline(20)                                                               // ExtremelyOversold
hline(30)                                                               // Oversold
hline(50)                                                               // Midline
hline(70)                                                               // Overbought
hline(80)                                                               // ExtremelyOverbought


upl = plot(up, "Upper Band", color = #3286c3, linewidth = 2)               // Upper Band
dnl = plot(dn, "Lower Band", color = #3286c3, linewidth = 2)               // Lower Band
midl = plot(mid, "Middle of Bands", color = #ffff00, linewidth = 2)      // Middle of Bands 

plot(slowMA, "Slow MA", color = #00AB08, linewidth=2)                       // Plot Slow MA
plot(fastMA, "Fast MA", color = #ff0000, linewidth=1)                         // Plot Fast MA